#!/usr/bin/env bash

if [ $# == 1 ]; then
	VERSION="$1"; shift
else
	echo ./make_release versao_nova >&2
	exit 1
fi

CURRENT_VERSION=($(cat version.txt | sed 's;\.;.;g'))

case "$VERSION" in
	patch)
		VERSION="${CURRENT_VERSION[0]}.${CURRENT_VERSION[1]}.$((${CURRENT_VERSION[2]}+1))"
	;;
	minor)
		VERSION="${CURRENT_VERSION[0]}.$((${CURRENT_VERSION[1]}+1)).0"
	;;
	major)
		VERSION="$((${CURRENT_VERSION[0]}+1)).0.0"
	;;
esac

printf "%s" "$VERSION" > version.txt

# Calculate versionCode (major*10000 + minor*100 + patch)
IFS='.' read -ra PARTS <<< "$VERSION"
VERSION_CODE=$((${PARTS[0]}*10000 + ${PARTS[1]}*100 + ${PARTS[2]}))

# Update build.gradle with new version
sed -i "s/versionCode [0-9]*/versionCode $VERSION_CODE/" app/build.gradle
sed -i "s/versionName \"[^\"]*\"/versionName \"$VERSION\"/" app/build.gradle

git add -A
git commit -sm "bump to $VERSION"
if [[ ! -v NO_TAG ]]; then
	git tag "$VERSION"
	git push --tag
fi
git push
