// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//   sqlc-gen-java 0.0.7

package com.biglucas.agena.db;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

@Generated("io.github.tandemdude.sqlc-gen-java")
public class Queries {
    private final java.sql.Connection conn;

    public Queries(java.sql.Connection conn) {
        this.conn = conn;
    }


    private static final String addHistoryEntry = """
        -- name: AddHistoryEntry :exec
        INSERT INTO history (url) VALUES (?)
        """;

    public void addHistoryEntry(
        @Nullable String url
    ) throws SQLException {
        var stmt = conn.prepareStatement(addHistoryEntry);
        stmt.setString(1, url);

        stmt.execute();
    }

    private static final String getHistoryLines = """
        -- name: GetHistoryLines :many
        SELECT url, accessed FROM history ORDER BY accessed DESC
        """;

    public record GetHistoryLinesRow(
        @Nullable String url,
        @Nullable OffsetDateTime accessed
    ) {}

    public List<GetHistoryLinesRow> getHistoryLines() throws SQLException {
        var stmt = conn.prepareStatement(getHistoryLines);

        var results = stmt.executeQuery();
        var retList = new ArrayList<GetHistoryLinesRow>();
        while (results.next()) {
            var ret = new GetHistoryLinesRow(
                results.getString(1),
                ((com.biglucas.agena.db.wrapper.AndroidResultSet)results).getObject(2, OffsetDateTime.class)
            );
            retList.add(ret);
        }

        return retList;
    }
}
